
title: LLM4S
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  LLM4S is a Scala LLM library.  Access the power of LLMs in the best language.
baseurl: ""
url: "https://llm4s.org"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
